### ISSUE TITLE
get_lowfee_reachable_unweighted_maxflows

### ISSUE THREAD

**Issue by kroese** [ajpwahqgbi/lightning-tools#10]
The function `get_lowfee_reachable_unweighted_maxflows` takes about 10 minutes to calculate on my PC.

The script is supposed to call this function for every other node, so 10.000 times for example. This means it will take years to finish. I'm sure this is not normal, so what can be the reason that `get_lowfee_reachable_unweighted_maxflows` is so slow in my case?

**Comment by ajpwahqgbi** [comment]
When this script was written, the network was much smaller. It was slow then but as you point out it is impossibly slow now.

There are a few things that could be done to improve the situation but the reality is that for this script to be tractable without major changes, you will have to further reduce the size of the graph considered in the analysis.

At the very least you should increase [`min_channels` and `min_capacity`](https://github.com/ajpwahqgbi/lightning-tools/blob/72e4aafe461e1544143b231c98fbb9c2bd22c527/channel-analysis/node-recommender/node_recommender.py#L24).

But even more aggressive graph pruning may be required. I would put any additional conditions for node inclusion in [`node_is_big_enough()`](https://github.com/ajpwahqgbi/lightning-tools/blob/72e4aafe461e1544143b231c98fbb9c2bd22c527/channel-analysis/node-recommender/node_recommender.py#L88) and additional overall graph pruning right after the call to [`get_lowfee_reachable_subgraph()`](https://github.com/ajpwahqgbi/lightning-tools/blob/72e4aafe461e1544143b231c98fbb9c2bd22c527/channel-analysis/node-recommender/node_recommender.py#L416) -- just further filter down `lowfee_nodes` and `lowfee_edges`.
