### ISSUE TITLE
Banned nodes

### ISSUE THREAD

**Issue by kroese** [ajpwahqgbi/lightning-tools#9]
The script includes a few banned nodes, like 1ML. But what is the rationale behind this? Does it speed up calculations? And do I need to ban every large node or just these two?

**Comment by ajpwahqgbi** [comment]
The rationale was that those nodes in particular *always* failed my payment attempts, no matter which channels I attempted to route through. That was some time ago, though, so you should re-evaluate at least tippin.me. 

Nodes that cannot route a payment should not be included in the analysis. Including them doesn't break anything, but it skews the results you receive.

Feel free to unban those nodes if you like or add more if you encounter other nodes that are similarly useless for routing.
